# Site settings
title: Wairarapa Sky
email: kaiora@wairarapasky.com
author: Andy Bateman
description: Astronomy Fun in the Wairarapa
url: https://www.wairarapasky.com

# Build settings
permalink: :title/
future: true

defaults:
  -
    values:
      theme: "dark"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
